Repository oSoc19/opt-horison, pull requests merged in 2019-07, with the labels that each got.

#3 Added basic support for point of interest files.
  data/dataset.js
  data/json/sets/swimming-pools.json
  data/json/sets/theatres.json
  data/json/sources.json
Labels: feature

#4 Added plannerjs library setup
  iso/isochrone.js
  lib/planner.js
Labels: feature

#5 added .vscode to gitignore
  .gitignore
  .vscode/launch.json
  .vscode/settings.json
Labels: feature

#6 Added support for environment files to store API keys
  .gitignore
  package-lock.json
  src/components/CustomMap/CustomMap.js
Labels: feature

#25 Feature/sidebar
  package-lock.json
  package.json
  public/index.html
  src/App.css
  src/App.js
  src/components/CustomMap/CustomMap.css
  src/components/CustomMap/CustomMap.js
  src/components/CustomMap/__tests__/MapSnapshotTest.js
  src/components/CustomMap/__tests__/MapTest.js
  src/components/CustomSidebar/CustomSidebar.css
  src/components/CustomSidebar/CustomSidebar.js
  src/components/CustomSidebar/index.js
  src/components/ExpandCollapseButton/ExpandCollapseButton.css
  src/components/ExpandCollapseButton/ExpandCollapseButton.js
  src/components/ExpandCollapseButton/index.js
Labels: feature

#31 Feature/user tab
  package-lock.json
  package.json
  src/App.js
  src/components/CustomSidebar/CustomSidebar.js
  src/components/CustomSidebar/ExpandCollapseButton/ExpandCollapseButton.css
  src/components/CustomSidebar/ExpandCollapseButton/ExpandCollapseButton.js
  src/components/CustomSidebar/ExpandCollapseButton/index.js
  src/components/CustomSidebar/POITab/POITab.css
  src/components/CustomSidebar/POITab/POITab.js
  src/components/CustomSidebar/POITab/index.js
  src/components/CustomSidebar/UserTab/ParticipantRow/ParticipantRow.css
  src/components/CustomSidebar/UserTab/ParticipantRow/ParticipantRow.js
  src/components/CustomSidebar/UserTab/ParticipantRow/index.js
  src/components/CustomSidebar/UserTab/TransportModeIcon/TransportModeIcon.css
  src/components/CustomSidebar/UserTab/TransportModeIcon/TransportModeIcon.js
  src/components/CustomSidebar/UserTab/TransportModeIcon/index.js
  src/components/CustomSidebar/UserTab/UserCreationModal/UserCreationForm/UserCreationForm
  src/components/CustomSidebar/UserTab/UserCreationModal/UserCreationForm/UserCreationForm.js
  src/components/CustomSidebar/UserTab/UserCreationModal/UserCreationForm/index.js
  src/components/CustomSidebar/UserTab/UserCreationModal/UserCreationModal.css
  src/components/CustomSidebar/UserTab/UserCreationModal/UserCreationModal.js
  src/components/CustomSidebar/UserTab/UserCreationModal/index.js
  src/components/CustomSidebar/UserTab/UserTab.css
  src/components/CustomSidebar/UserTab/UserTab.js
  src/components/CustomSidebar/UserTab/index.js
  src/models/User.js
  src/models/index.js
Labels: feature

#33 Feature/visualise poi
  data/dataset.js
  data/json/sets/swimming-pools.json
  data/json/sets/theatres.json
  data/json/sources.json
  iso/isochrone.js
  lib/planner.js
  package-lock.json
  package.json
  src/assets/beer.svg
  src/components/CustomMap/CustomMap.js
  src/components/CustomMap/index.js
  src/components/IsochroneLayer/IsochroneLayer.js
  src/components/IsochroneLayer/index.js
  src/components/PoiLayer/PoiLayer.js
  src/components/PoiLayer/index.js
  src/data/json/bars.json
  src/data/json/cafes.json
  src/data/json/restos.json
  src/data/pointsets.js
  src/iso/Feature.js
  src/iso/FeatureCollection.js
  src/iso/Geometry.js
  src/iso/isochrone.js
Labels: feature

#38 integrated isochrone code
  src/components/CustomMap/CustomMap.js
  src/data/pointsets.js
  src/iso/isochrone.js
  src/iso/isochrone_old.js
Labels: feature

#39 Feature/draggable marker
  package-lock.json
  src/App.js
  src/components/CustomMap/CustomMap.js
  src/components/CustomSidebar/CustomSidebar.js
  src/components/CustomSidebar/UserTab/UserCreationModal/UserCreationForm/UserCreationForm.js
  src/components/CustomSidebar/UserTab/UserCreationModal/UserCreationModal.js
  src/components/CustomSidebar/UserTab/UserTab.js
  src/models/User.js
Labels: feature

#45 Fix draggable marking rolling back to previous state
  src/App.js
Labels: bug

#50 Feature/poi interface
  package-lock.json
  src/App.js
  src/components/CustomMap/CustomMap.js
  src/components/CustomSidebar/CustomSidebar.js
  src/components/CustomSidebar/POITab/POITab.js
  src/components/IsochroneLayer/IsochroneLayer.js
  src/components/PoiLayer/PoiLayer.js
  src/data/pointsets.js
Labels: feature

#52 Feature/perf improve refactoring
  package-lock.json
  src/App.css
  src/App.js
  src/components/CustomMap/CustomMap.js
  src/components/CustomMap/IsochroneLayer/IsochroneLayer.js
  src/components/CustomMap/IsochroneLayer/index.js
  src/components/CustomMap/PoiLayer/PoiLayer.js
  src/components/CustomMap/PoiLayer/index.js
  src/components/CustomSidebar/CustomSidebar.js
  src/components/CustomSidebar/UserTab/ParticipantRow/ParticipantRow.js
  src/components/CustomSidebar/UserTab/ParticipantRow/index.js
  src/components/CustomSidebar/UserTab/TransportModeIcon/TransportModeIcon.js
  src/components/CustomSidebar/UserTab/UserCreationModal/UserCreationForm/UserCreationForm.css
  src/components/CustomSidebar/UserTab/UserCreationModal/UserCreationForm/UserCreationForm.js
  src/components/CustomSidebar/UserTab/UserTab.js
  src/iso/FeatureCollection.js
  src/models/User.js
Labels: breaking-change, bug-fixes, enhancement, feature, in progress

#53 Feature/isochrones
  package-lock.json
  package.json
  src/iso/isochrone.js
  src/models/ResultContainer.js
Labels: breaking-change, done, feature

#54 Update index.js
  src/models/index.js
Labels: bug-fixes, in progress

#56 Update ResultContainer.js
  src/models/ResultContainer.js
Labels: bug, bug-fixes, in progress

#58 fixed some integration bugs
  package-lock.json
  src/App.js
  src/components/CustomMap/CustomMap.js
  src/components/CustomMap/IsochroneLayer/IsochroneLayer.js
  src/data/pointsets.js
  src/iso/isochrone.js
  src/models/ResultContainer.js
Labels: bug-fixes

#60 Feature/processes linking
  package-lock.json
  src/App.js
  src/components/CustomMap/CustomMap.js
  src/iso/isochrone.js
  src/iso/isochrone_old.js
  src/models/Coordinates.js
  src/models/Feature.js
  src/models/FeatureCollection.js
  src/models/Geometry.js
  src/models/User.js
  src/models/index.js
Labels: breaking-change, feature, in progress

#61 Feature/isochrone layers
  src/components/CustomMap/CustomMap.js
  src/components/CustomMap/IsochroneLayer/IsochroneLayer.js
Labels: feature

#63 implement refresh map button
  src/App.js
  src/components/CustomMap/CustomMap.js
  src/components/CustomMap/IsochroneLayer/IsochroneLayer.js
  src/components/CustomMap/PoiLayer/PoiLayer.js
  src/components/CustomSidebar/CustomSidebar.js
  src/components/CustomSidebar/POITab/POITab.js
  src/components/CustomSidebar/POITab/PointOfInterest/PointOfInterest.js
  src/components/CustomSidebar/UserTab/UserCreationModal/UserCreationForm/UserCreationForm.js
  src/components/CustomSidebar/UserTab/UserCreationModal/UserCreationModal.js
  src/components/CustomSidebar/UserTab/UserTab.js
  src/iso/isochrone.js
  src/models/Coordinates.js
  src/models/User.js
Labels: feature, in progress

#67 Hotfix/delete user
  src/App.js
  src/components/CustomMap/CustomMap.js
  src/components/CustomMap/IsochroneLayer/IsochroneLayer.js
  src/models/User.js
Labels: bug-fixes

#74 Feature/margot styling
  public/favicon.ico
  src/App.js
  src/assets/logo.svg
  src/components/CustomMap/CustomMap.js
  src/components/CustomMap/IsochroneLayer/IsochroneLayer.js
  src/components/CustomMap/OverlapLayer/OverlapLayer.js
  src/components/CustomMap/PoiLayer/PoiLayer.js
  src/components/CustomSidebar/CustomSidebar.css
  src/components/CustomSidebar/CustomSidebar.js
  src/components/CustomSidebar/ExpandCollapseButton/ExpandCollapseButton.css
  src/components/CustomSidebar/ExpandCollapseButton/ExpandCollapseButton.js
  src/components/CustomSidebar/POITab/POITab.js
  src/components/CustomSidebar/POITab/PointOfInterest/PointOfInterest.css
  src/components/CustomSidebar/POITab/PointOfInterest/PointOfInterest.js
  src/components/CustomSidebar/UserTab/ParticipantRow/ParticipantRow.js
  src/components/CustomSidebar/UserTab/TransportModeIcon/TransportModeIcon.js
  src/components/CustomSidebar/UserTab/UserTab.js
  src/data/pointsets.js
Labels: feature

#77 Added documentation for IsochroneLayer, OverlapLayer and pointsets
  src/components/CustomMap/IsochroneLayer/IsochroneLayer.js
  src/components/CustomMap/OverlapLayer/OverlapLayer.js
  src/data/pointsets.js
Labels: docs

#80 Feature/modal restyling
  public/index.html
  src/App.css
  src/components/CustomMap/CustomMap.js
  src/components/CustomSidebar/UserTab/UserCreationModal/UserCreationForm/TransportModeGroup/TransportModeButton/TransportModeButton.css
  src/components/CustomSidebar/UserTab/UserCreationModal/UserCreationForm/TransportModeGroup/TransportModeButton/TransportModeButton.js
  src/components/CustomSidebar/UserTab/UserCreationModal/UserCreationForm/TransportModeGroup/TransportModeButton/index.js
  src/components/CustomSidebar/UserTab/UserCreationModal/UserCreationForm/TransportModeGroup/TransportModeGroup.css
  src/components/CustomSidebar/UserTab/UserCreationModal/UserCreationForm/TransportModeGroup/TransportModeGroup.js
  src/components/CustomSidebar/UserTab/UserCreationModal/UserCreationForm/TransportModeGroup/index.js
  src/components/CustomSidebar/UserTab/UserCreationModal/UserCreationForm/UserCreationForm.css
  src/components/CustomSidebar/UserTab/UserCreationModal/UserCreationForm/UserCreationForm.js
  src/components/CustomSidebar/UserTab/UserCreationModal/UserCreationForm/index.js
  src/components/CustomSidebar/UserTab/UserCreationModal/UserCreationModal.js
  src/iso/isochrone.js
  src/models/User.js
Labels: feature

#85 change text
  index.html
Labels: feature
